# This is a test makefile for compilation of some c++
# files


# Define makefile varible for compilator
# 
CC = gcc

# Define makefile variable for compilation flags
# 
CFLAGS = -g

# Define rule for .cpp to .o files
# 

# Define source files
# 

# Define out path
# 

# Define the copilation of the files ->
# 

